---
format:
  html:
    css: styles.css
    toc: false
    page-layout: article
---

::: page-header
# LATEST NEWS
:::

::: {.list-item-spaced} 
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7456165289509011456"
  title="Embedded post"></iframe>
:::


::: {.list-item-spaced} 
Recent Research Acceptances at ASTRA 2026 and SPE ATCE 2026

I am pleased to announce that two of my recent research papers have been accepted for presentation at upcoming conferences later this year.

The paper titled "Design Optimization of Automotive Seat Vibration Isolators for Improved Ride Comfort" (Paper ID: 181) has been officially accepted for an oral presentation at ASTRA 2026. This event will take place at the Indian Institute of Space Science and Technology (IIST).

Additionally, my work on predictive modeling, titled "Time-series Transformer Models For Predicting Transient Greenhouse Gas Emissions" (Paper Number: SPE-234073-MS), has been accepted as a Knowledge Sharing Electronic Poster (ePoster). I will be presenting this research at the 2026 SPE Annual Technical Conference and Exhibition, which will be held from October 21–23, 2026, in Houston, Texas, USA. The final manuscript for this proceeding is scheduled for submission by August 24, 2026.

I look forward to sharing these findings and engaging with fellow researchers and industry professionals at both events.
:::



::: {.list-item-spaced} 
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:share:7416848282158796803"
  title="Embedded post"></iframe>
:::


::: {.list-item-spaced} 
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:share:7367156104704741376"
  title="Embedded post"></iframe>
:::


::: {.list-item-spaced}
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:activity:7363068619066392576"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:activity:7363049498551472129"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}  
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:share:7348144627666849793"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}    
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:share:7296608686058131456"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}  
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:share:7285353598190809088"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}    
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:activity:7271931663054438400"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}  
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:share:7267065814774607872"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}    
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:activity:7253263865034022913"
  title="LinkedIn post embed"></iframe>
:::


::: {.list-item-spaced}    
<iframe class="embed-container iframe-embed"
  src="https://www.linkedin.com/embed/feed/update/urn:li:activity:7252926208563167232"
  title="LinkedIn post embed"></iframe>
:::







::: {.button-container}
<a href="home.qmd" class="btn-custom">Home →</a>
:::
