---
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false
    page-layout: article
---

::: page-header
# OPPORTUNITIES
:::

We are a newly established lab and actively seeking dedicated students with a strong interest in computational mechanics, topology optimization, and data-driven modeling. Our lab focuses on developing of intrusive and nonintrusive data-driven methods that retain physical accuracy while enabling significant computational speed-ups. If you have experience or a keen interest in these areas, we encourage you to consider joining our collaborative environment. We value rigorous inquiry, thoughtful problem-solving, and a commitment to advancing combustion technology. For more information on opportunities with our team, please feel free to reach out.



::: {.panel-tabset}

### PhD

We have openings for highly motivated PhD candidates to work on cutting-edge research. You will be asked to upload your CV, transcripts, and a statement of purpose.

<br>

<div class="text-center">
[**Apply for a PhD Position**](https://forms.gle/VWce1eHfuNnoYpM67){.btn .btn-custom .btn-lg target="_blank" rel="noopener noreferrer"}
</div>

### MTech

We are seeking MTech students for project work. This is an excellent opportunity to gain hands-on research experience. You will be asked to upload your CV and transcripts.

<br>

<div class="text-center">
[**Apply for an MTech Position**](https://forms.gle/RgAp7bdQJ3inCHm69){.btn .btn-custom .btn-lg target="_blank" rel="noopener noreferrer"}
</div>


### Intern

Students from across the nation are welcome to apply for internships at the D-Cubed Lab by filling out the application form below. Please do not email us to apply for internships, as all such emails will be ignored. Applicants will be contacted if there are some openings and their application is found to be relevant to the project at hand. 

**Please note** that the internships will typically be unpaid/self-funded internships.

<br>

<div class="text-center">
[**Apply for an Internship**](https://forms.gle/NNiyJa6LqNXJBzBD9){.btn .btn-custom .btn-lg target="_blank" rel="noopener noreferrer"}
</div>

:::