---
title: "Publications"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header: head.html
    include-after-body: publications-script.html # We will put the modal code here
    toc: false
    page-layout: article
resources:
  - publications.js
  - publications-script.html
---

::: pub-controls
<select id="pub-type"> <option value="">All Types</option> <option>Journal</option> <option>Preprint</option> <option>Refereed Proceeding</option> <option>Book Chapter</option> <option>Presentation</option> </select>

<select id="pub-year"> <option value="">All Years</option> <option>2025</option> <option>2024</option> <option>2023</option> <option>2022</option> <option>2021</option> <option>2020</option> <option>2019</option> <option>2011</option> </select>
:::

## Journals

:::::: {.pub-item data-year="2025" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, and Cusumano J. (2025J).\
*Journal of Nonlinear Mechanics*\
[Model reduction of a flexible nonsmooth oscillator recovers its entire bifurcation structure](publications/model_reduction.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_7">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_7">Abstract</a> <a href="https://doi.org/10.1016/j.ijnonlinmec.2025.105194" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_7 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2025,
  title = {Model reduction of a flexible nonsmooth oscillator recovers its entire bifurcation structure},
  ISSN = {0020-7462},
  url = {http://dx.doi.org/10.1016/j.ijnonlinmec.2025.105194},
  DOI = {10.1016/j.ijnonlinmec.2025.105194},
  journal = {International Journal of Non-Linear Mechanics},
  publisher = {Elsevier BV},
  author = {Bhattacharyya,  Suparno and Cusumano,  Joseph P.},
  year = {2025},
  month = jul,
  pages = {105194}
}</code></pre>
```
:::

::: {#abs-bhattacharyya_7 .d-none}
<p>We study the reduced order modeling of a nonlinear flexible oscillator in which a Bernoulli-Euler beam is subjected to a position-triggered kick force and a piecewise restoring force at its tip. The resulting nonsmooth boundary conditions can generally be expected to excite many degrees of freedom. The system is modeled as piecewise linear with different boundary conditions determining different regions of a hybrid phase space. With kick strength as parameter, its bifurcation diagram is found to exhibit a range of periodic and chaotic behaviors. Proper orthogonal decomposition (POD) is used to estimate the system's intrinsic dimensionality. However, conventional POD's purely statistical analysis of spatial covariance does not guarantee accuracy of reduced order models (ROMs). We therefore augment POD by employing a previously-developed energy closure criterion that selects ROM dimension by ensuring approximate energy balance on the reduced subspace. This physics-based criterion yields accurate ROMs with 8 degrees of freedom. Remarkably, we find that ROMs formulated at particular values of the kick strength can nevertheless reconstruct the entire bifurcation structure of the original nonlinear structural system. We thus show that energy closure analysis reliably yields effective dimension estimates and, thereby, ROMs that are robust across stability transitions, including even period doubling cascades to chaos.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2025" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Chatterjee A. (2025J).\
*Journal of Applied Mechanics.*\
[Experimental study of damping enhancement in aluminium rods by knurling](publications/experimental_study.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_1">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_1">Abstract</a> <a href="https://asmedigitalcollection.asme.org/appliedmechanics/article-abstract/doi/10.1115/1.4068859/1218680/Experimental-study-of-damping-enhancement-in?redirectedFrom=fulltext" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_1 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2025,
    author = {Bhattacharyya, Suparno and Chatterjee, Anindya},
    title = {Experimental Study of Damping Enhancement in Aluminum Rods by Knurling},
    journal = {Journal of Applied Mechanics},
    volume = {92},
    number = {10},
    pages = {101003},
    year = {2025},
    month = {06}
}</code></pre>
```
:::

::: {#abs-bhattacharyya_1 .d-none}
<p>This paper is motivated by an interest in the damping behaviour of lightly damped metal components. Some anecdotal evidence suggests that near surface plastic deformation, such as in shot peening, might increase the damping of metallic components. Here we have studied the damping behaviour of slender aluminum rods in the first free-free mode, suspended at a nodal point. Three types of rods were studied: a plain rod, a knurled rod, and a plain rod wrapped with viscoelastic tape. Two rods of each type were tested. Free vibration responses of the struck rods were measured and recorded after analog and digital filtering. Damping coefficients were determined from ten measurements per rod. Results were consistent within each rod pair but significantly differed across rod types. Knurled rods exhibited approximately 1.6 times the damping of plain rods, while viscoelastic tape increased damping by a factor of 2.3. The possible role of surface roughness-induced air damping for knurled rods was investigated analytically as well as numerically (using FLUENT). It was concluded that air damping effects were weak; and that knurling, which is a near-surface deformation process, can significantly increase the damping in metal components. Although the increase is lower than it is with viscoelastic damping layers, near-surface deformation induced damping may be preferred in some applications.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2025" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**\[Bhattacharyya S.\]**, Tao J., Gildin E., Ragusa J. (2025J).\
*Archives of Computational Methods in Engineering.*\
[Hyper-reduction Techniques for Efficient Simulation of Large-Scale Engineering Systems](publications/hyperreduction_techniques.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_2">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_2">Abstract</a> <a href="site coming soon" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_2 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2025,
  title = {Hyper-Reduction Techniques for Efficient Simulation of Large-Scale Engineering Systems},
  ISSN = {1886-1784},
  url = {http://dx.doi.org/10.1007/s11831-025-10299-4},
  DOI = {10.1007/s11831-025-10299-4},
  journal = {Archives of Computational Methods in Engineering},
  publisher = {Springer Science and Business Media LLC},
  author = {Bhattacharyya,  Suparno and Tao,  Jian and Gildin,  Eduardo and Ragusa,  Jean C.},
  year = {2025},
  month = jul 
}</code></pre>
```
:::

::: {#abs-bhattacharyya_2 .d-none}
<p>Reduced-order models (ROMs) offer compact representations of complex engineering systems governed by partial differential equations or high-dimensional ordinary differential equations enabling efficient simulations of otherwise computationally intensive problems. These models are typically constructed by projecting the high-dimensional governing equations onto reduced subspaces derived using techniques such as Singular Value Decomposition (SVD) or Proper Orthogonal Decomposition (POD). However, conventional ROMs struggle with nonlinear systems due to the high computational cost of repeatedly accessing high-dimensional solution spaces for nonlinear term evaluations. Hyper-reduction methods address this challenge by efficiently approximating nonlinear term evaluations, significantly improving ROM performance. They are also essential for solving large parametric linear problems that lack an efficient parameter-affine decomposition. This paper provides a comprehensive overview of hyper-reduction algorithms, emphasizing both their theoretical foundations and practical implementations in academic research and industry. With the rapid advancement of data-driven methods, reduced-order modeling has become indispensable for analyzing and simulating large-scale systems, including fluid dynamics, thermal processes, and structural mechanics. As the demand for efficient computational tools in science and engineering continues to grow, a detailed discussion of hyper-reduction techniques is both timely and valuable. The paper explores state-of-the-art hyper-reduction techniques, including discrete empirical interpolation methods (DEIM), energy-conserving sampling and weighting (ECSW), and emerging machine learning-based approaches. A nonlinear parametric heat conduction example is presented to illustrate the implementation of these methods. The analysis evaluates their strengths and weaknesses using standard metrics, providing insights into their practical utility. Finally, the paper concludes by discussing future research directions and potential applications of hyper-reduction, including its integration with real-time simulations and digital twin systems.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2024" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**\[Khawale R., Bhattacharyya S.\]**, Rai R., Dargush G. (2024J).\
*Computers & Structures.*\
[Efficient dynamic topology optimization of 2D metamaterials based on complementary-energy formulation](publications/efficient_dynamic.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_3">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_3">Abstract</a> <a href="https://www.sciencedirect.com/science/article/abs/pii/S0045794924001007" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_3 .d-none}
```{=html}
<pre><code>@article{Khawale2024,
  title = {Efficient dynamic topology optimization of 2D metamaterials based on a complementary energy formulation},
  volume = {299},
  ISSN = {0045-7949},
  url = {http://dx.doi.org/10.1016/j.compstruc.2024.107371},
  DOI = {10.1016/j.compstruc.2024.107371},
  journal = {Computers &amp; Structures},
  publisher = {Elsevier BV},
  author = {Khawale,  Raj Pradip and Bhattacharyya,  Suparno and Rai,  Rahul and Dargush,  Gary F.},
  year = {2024},
  month = aug,
  pages = {107371}
}</code></pre>
```
:::

::: {#abs-bhattacharyya_3 .d-none}
<p>The advent of additive manufacturing has revolutionized the design and development of hierarchical structures, with potential applications in compliant, auxetic, and band-gap structures. This paper presents an innovative approach to developing a dynamic Topology Optimization (TO) framework for designing printable lattice structures that exhibit specific dynamic properties. Utilizing parametrically defined filament-based unit cell structures for topology optimization, we achieve desired natural frequency bandgaps in the structures composed of these unit cells. To enhance computational efficiency, we employ a complementary energy-based formulation to (semi)analytically derive the flexibility and stiffness matrices of the unit cell structure, thus, eliminating extensive finite element discretization. Consequently, a wide variety of parametrically defined filament-based meso-structures can be mathematically explored. We apply this innovative framework specifically for band-gap maximization of 2D lattice structures. By tuning the geometry within each cell using TO, we maximize the band gap. Our results show the potential of this approach to create more efficient and effective hierarchical structures with desired band-gap properties.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2022" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Cusumano J. P. (2022J).\
*ASME Journal of Vibration and Acoustics.*\
[Experimental Implementation of Energy Closure Analysis for Reduced Order Modeling](publications/experimental_implementation.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_4">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_4">Abstract</a> <a href="https://www.researchgate.net/publication/359828494_Experimental_Implementation_of_Energy_Closure_Analysis_for_Reduced_Order_Modeling" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_4 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2022,
  title = {Experimental Implementation of Energy Closure Analysis for Reduced Order Modeling},
  volume = {144},
  ISSN = {1528-8927},
  url = {http://dx.doi.org/10.1115/1.4054295},
  DOI = {10.1115/1.4054295},
  number = {5},
  journal = {Journal of Vibration and Acoustics},
  publisher = {ASME International},
  author = {Bhattacharyya,  Suparno and Cusumano,  Joseph. P.},
  year = {2022},
  month = may 
}</code></pre>
```
:::

::: {#abs-bhattacharyya_4 .d-none}
<p>Reduced order models (ROMs) provide an efficient, kinematically condensed representation of computationally expensive high dimensional dynamical systems; however, their accuracy depends crucially on the accurate estimation of their dimension. We here demonstrate how the energy closure criterion, developed in our prior work, can be experimentally implemented to accurately estimate the dimension of ROMs obtained using the proper orthogonal decomposition (POD). We examine the effect of using discrete data with and without measurement noise, as will typically be gathered in an experiment or numerical simulation, on estimating the degree of energy closure on a candidate reduced subspace. To this end, we used a periodically kicked Euler-Bernoulli beam with Rayleigh damping as the model system, and studied ROMs obtained by applying POD to discrete displacement field data obtained from simulated numerical experiments. An improved method for quantifying the degree of energy closure is presented: the convergence of energy input to or dissipated from the system is obtained as a function of the subspace dimension, and the dimension capturing a predefined percentage of either energy is selected as the ROM-dimension. This method was found to be more robust to data discretization error and measurement noise. The data processing necessary for the experimental application of energy closure analysis is discussed in detail. We show ROMs formulated from the simulated data using our approach accurately capture the dynamics of the beam for different sets of parameter values.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2021" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Cusumano J. (2021J).\
*ASME Journal of Vibration and Acoustics.*\
[An Energy Closure Criterion for Model Reduction of a Kicked Euler-Bernoulli Beam](publications/energy_closure.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_5">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_5">Abstract</a> <a href="https://asmedigitalcollection.asme.org/vibrationacoustics/article-abstract/143/4/041001/1087802/An-Energy-Closure-Criterion-for-Model-Reduction-of?redirectedFrom=fulltext" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_5 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2020,
  title = {An Energy Closure Criterion for Model Reduction of a Kicked Euler–Bernoulli Beam},
  volume = {143},
  ISSN = {1528-8927},
  url = {http://dx.doi.org/10.1115/1.4048663},
  DOI = {10.1115/1.4048663},
  number = {4},
  journal = {Journal of Vibration and Acoustics},
  publisher = {ASME International},
  author = {Bhattacharyya,  Suparno and Cusumano,  Joseph P.},
  year = {2020},
  month = nov 
}</code></pre>
```
:::

::: {#abs-bhattacharyya_5 .d-none}
<p>Reduced order models (ROMs) can be simulated with lower computational cost while being more amenable to theoretical analysis. Here, we examine the performance of the proper orthogonal decomposition (POD), a data-driven model reduction technique. We show that the accuracy of ROMs obtained using POD depends on the type of data used and, more crucially, on the criterion used to select the number of proper orthogonal modes (POMs) used for the model. Simulations of a simply supported Euler–Bernoulli beam subjected to periodic impulsive loads are used to generate ROMs via POD, which are then simulated for comparison with the full system. We assess the accuracy of ROMs obtained using steady-state displacement, velocity, and strain fields, tuning the spatiotemporal localization of applied impulses to control the number of excited modes in, and hence the dimensionality of, the system’s response. We show that conventional variance-based mode selection leads to inaccurate models for sufficiently impulsive loading and that this poor performance is explained by the energy imbalance on the reduced subspace. Specifically, the subspace of POMs capturing a fixed amount (say, 99.9%) of the total variance underestimates the energy input and dissipated in the ROM, yielding inaccurate reduced-order simulations. This problem becomes more acute as the loading becomes more spatio-temporally localized (more impulsive). Thus, energy closure analysis provides an improved method for generating ROMs with energetics that properly reflect that of the full system, resulting in simulations that accurately represent the system’s true behavior.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2011" data-type="Journal"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Naskar T.K. (2011J).\
*International Journal of Mechanical and Industrial Engineering.*\
[Analysis of the Effect of Number of Knots in a Trajectory on Motion Characteristics of a 3R Planar Manipulator](publications/planar_manipulator.qmd)

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bhattacharyya_6">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abs-bhattacharyya_6">Abstract</a> <a href="https://www.researchgate.net/publication/348174810_Analysis_of_the_Effect_of_Number_of_Knots_in_a_Trajectory_on_Motion_Characteristics_of_a_3R_Planar_Manipulator" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bhattacharyya_6 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2012,
  title = {Analysis of the Effect of Number of Knots in a Trajectory on Motion Characteristics of a 3R Planar Manipulator},
  ISSN = {2231-6477},
  url = {http://dx.doi.org/10.47893/IJMIE.2012.1031},
  DOI = {10.47893/ijmie.2012.1031},
  journal = {International Journal of Mechanical and Industrial Engineering},
  publisher = {Institute for Project Management Pvt. Ltd},
  author = {Bhattacharyya,  Suparno C and Naskar,  Tarun Kanti},
  year = {2012},
  month = jan,
  pages = {150–155}
}</code></pre>
```
:::

::: {#abs-bhattacharyya_6 .d-none}
<p>The paper presents a method of trajectory planning and motion characteristics of a robotic manipulator. Main objective is to study the motion characteristics of a manipulator and to explore the scope of minimization of jerk. 8th order polynomial is considered for the trajectory design and the effect of number of intermediate knots between start and final positions of a 3R manipulator within the workspace is studied. Displacements, velocities, accelerations and jerk of end-effectors on a linear path are presented. The simulation for motion of the manipulator is done with the help of AutoLISP on AutoCAD platform.</p>
:::
:::::
::::::

## Preprints

:::: {.pub-item data-year="2025" data-type="Preprint"}
[📄]{.pub-icon}

::: pub-content
*{No Preprints Available Right Now }*\
:::
::::

## Refereed Proceedings

:::::: {.pub-item data-year="2024" data-type="Refereed Proceeding"}
[📄]{.pub-icon}

::::: pub-content
Huhn Q., **Bhattacharyya S.**, Ragusa J. (2024C).\
*Transactions of the American Nuclear Society*\
[Hyperreduction for Neutron Transport](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite_4">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract_4">Abstract</a> <a href="https://www.ans.org/pubs/transactions/article-57015/" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite_4 .d-none}
```{=html}
<pre><code>@article{HuhnBhattacharyyaRagusa2024,
  title   = {Hyperreduction for Neutron Transport},
  author  = {Huhn, Quincy and Bhattacharyya, Suparno and Ragusa, Jean},
  journal = {Transactions of the American Nuclear Society},
  volume  = {131},
  number  = {1},
  pages   = {462--465},
  month   = nov,
  year    = {2024},
  doi     = {10.13182/T131-46086},
}</code></pre>
```
:::

::: {#abstract_4 .d-none}
<p>{Not Available Right Now }</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2023" data-type="Refereed Proceeding"}
[📄]{.pub-icon}

::::: pub-content
Khawale R.P., **Bhattacharyya S.**, Bielecki D., Rai R., Dargush G. (2023C).\
*Society for Experimental Mechanics Series*\
[Efficient Methods for Flexibility-Based Meso-scale Dynamic Modeling](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite_3">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract_3">Abstract</a> <a href="https://link.springer.com/chapter/10.1007/978-3-031-37007-6_13#citeas" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite_3 .d-none}
```{=html}
<pre><code>@inbook{Khawale2023,
  title = {Efficient Methods for Flexibility-Based Meso-scale Dynamic Modeling},
  ISBN = {9783031370076},
  ISSN = {2191-5652},
  url = {http://dx.doi.org/10.1007/978-3-031-37007-6_13},
  DOI = {10.1007/978-3-031-37007-6_13},
  booktitle = {Special Topics in Structural Dynamics &amp; Experimental Techniques,  Volume 5},
  publisher = {Springer Nature Switzerland},
  author = {Khawale,  Raj Pradip and Bhattacharyya,  Suparno and Bielecki,  Dustin and Rai,  Rahul and Dargush,  Gary},
  year = {2023},
  month = jun,
  pages = {125–127}
}</code></pre>
```
:::

::: {#abstract_3 .d-none}
<p>With the advent of additive manufacturing comes the opportunity to design novel components and systems, especially when one considers hierarchical structures. Our recent work Bielecki et al. (Struct Multidiscip Optim 64(6):3473–3487, 2021); Bielecki et al. (Multiscale compliant topology optimization for twistable wing design. In: AIAA AVIATION 2021 FORUM (2021), pp. 2429) has demonstrated a highly effective framework of multi-scale topology optimization for designing such structures. In this work, we focus on enhancing the efficiency of the analysis at the meso-scale by introducing a new complementary energy formulation. This enables the computationally attractive formulation of parametrically defined filament-based meso-structures of arbitrary path within each unit cell. We have implemented this framework for dynamical problems, specifically, for modal analysis. We considered mass lumping and static condensation within the unit meso-scale cells. Computational experiments are provided to test the robustness, accuracy, and computational efficiency of the approach.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2019" data-type="Refereed Proceeding"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Cusumano J. (2019C).\
*Proceedings of the ASME IDETC*\
[The Importance of Energy Criteria for Selecting Modes in Reduced Order Modeling](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite_2">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract_2">Abstract</a> <a href="https://asmedigitalcollection.asme.org/IDETC-CIE/proceedings-abstract/IDETC-CIE2019/59285/1070228" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite_2 .d-none}
```{=html}
<pre><code>@inproceedings{Bhattacharyya2019,
  series = {IDETC-CIE2019},
  title = {The Importance of Energy Criteria for Selecting Modes in Reduced Order Modeling},
  url = {http://dx.doi.org/10.1115/DETC2019-98140},
  DOI = {10.1115/detc2019-98140},
  booktitle = {Volume 8: 31st Conference on Mechanical Vibration and Noise},
  publisher = {American Society of Mechanical Engineers},
  author = {Bhattacharyya,  Suparno and Cusumano,  Joseph P.},
  year = {2019},
  month = aug,
  collection = {IDETC-CIE2019}
}</code></pre>
```
:::

::: {#abstract_2 .d-none}
<p>We study the performance of the proper orthogonal decomposition when used for model reduction of an Euler-Bernoulli beam subjected to periodic impulses. We assess the accuracy of reduced order models (ROMs) obtained using steady-state displacement time series. The spatiotemporal localization of the applied impulses is tuned to control the number of excited modes in, and hence the effective dimensionality of, the system’s response. We find that when the impacts are significantly localized (i.e., are more impulsive), the conventional variance-based mode selection criterion can lead to inaccurate ROMs. We show that this arises when the reduced subspace capturing a fixed amount (say, 99.9%) of the total data variance underestimates the energy input and/or dissipated in the ROM, leading to energy imbalance. We thus propose a new energy closure criterion that provides an improved method for generating ROMs. The energetics of the resulting ROMs properly reflect those of the full system, and yield simulations that accurately represent the system’s true behavior.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2011" data-type="Refereed Proceeding"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Naskar T.K. (2011C).\
*Proceedings of the 9th International Conference on Mechanical Engineering*\
[The effect of number of knots in a polynomial trajectory on motion characteristics of robotic manipulators](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite_1">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract_1">Abstract</a> <a href="https://www.researchgate.net/publication/348174810_Analysis_of_the_Effect_of_Number_of_Knots_in_a_Trajectory_on_Motion_Characteristics_of_a_3R_Planar_Manipulator" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite_1 .d-none}
```{=html}
<pre><code>@article{Bhattacharyya2012,
  title = {Analysis of the Effect of Number of Knots in a Trajectory on Motion Characteristics of a 3R Planar Manipulator},
  ISSN = {2231-6477},
  url = {http://dx.doi.org/10.47893/IJMIE.2012.1031},
  DOI = {10.47893/ijmie.2012.1031},
  journal = {International Journal of Mechanical and Industrial Engineering},
  publisher = {Institute for Project Management Pvt. Ltd},
  author = {Bhattacharyya,  Suparno C and Naskar,  Tarun Kanti},
  year = {2012},
  month = jan,
  pages = {150–155}
}</code></pre>
```
:::

::: {#abstract_1 .d-none}
<p>The paper presents a method of trajectory planning and motion characteristics of a robotic manipulator. Main objective is to study the motion characteristics of a manipulator and to explore the scope of minimization of jerk. 8th order polynomial is considered for the trajectory design and the effect of number of intermediate knots between start and final positions of a 3R manipulator within the workspace is studied. Displacements, velocities, accelerations and jerk of end-effectors on a linear path are presented. The simulation for motion of the manipulator is done with the help of AutoLISP on AutoCAD platform.</p>
:::
:::::
::::::

## Book Chapters

:::::: {.pub-item data-year="2023" data-type="Book Chapter"}
[📄]{.pub-icon}

::::: pub-content
**Bhattacharyya S.**, Kumar, A. (2023B).\
*MEMS Applications in Electronics and Engineering.*\
[Mechanics of Materials Considerations in MEMS-Based Medical Devices](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bc_3">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract-bc_3">Abstract</a> <a href="https://www.researchgate.net/publication/368998492_Mechanics_of_Materials_Considerations_in_MEMS-Based_Medical_Devices" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bc_3 .d-none}
```{=html}
<pre><code>@inbook{Bhattacharyya2023,
  title = {Mechanics of Materials Considerations in MEMS-Based Medical Devices},
  ISBN = {9780735424395},
  url = {http://dx.doi.org/10.1063/9780735424395_005},
  DOI = {10.1063/9780735424395_005},
  booktitle = {MEMS Applications in Electronics and Engineering},
  publisher = {AIP Publishing},
  author = {Bhattacharyya,  Suparno and Kumar,  Arkadeep},
  year = {2023},
  pages = {1–26}
}</code></pre>
```
:::

::: {#abstract-bc_3 .d-none}
<p>DESCRIPTION In recent years, medical devices have seen unprecedented use of MEMS-based sensors. Such devices are indispensable in many invasive applications such as localized drug delivery, angioplasty, and implant-based blood pressure measurement, as well as in many non-invasive applications such as pharmaceutical research, cell culture, and medical imaging. These devices are essential for continuously monitoring critical patients, such as those with cardiac diseases, respiratory illnesses (e.g., COVID patients), etc., typically treated in Intensive Care Units. The functionality of many critical care equipment such as ventilators, heart rate monitors, and dialysis machines is based on Bio-MEMS sensors. Here, we review two Bio-MEMS sensors ubiquitously present across a variety of medical devices: MEMS pressure sensors and MEMS accelerometer sensors. We discuss the different fields of application of these sensors, describe their working principles, discuss the material selection considerations, and most importantly, analyze their reliability. Accuracy and reliability are two critical aspects of sensor performance. We discuss in detail the reliability of bio-MEMS devices from a mechanics point of view. We discuss multiple mechanical failure modes that result in the loss of reliability and functionality of these MEMS sensors. Moreover, we discuss the current challenges and prospects for future research in this field.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2023" data-type="Book Chapter"}
[📄]{.pub-icon}

::::: pub-content
Basu A.K., **Bhattacharyya S.**. (2023B).\
*MEMS Applications in Electronics and Engineering.*\
[Scaling Law](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bc_2">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract-bc_2">Abstract</a> <a href="https://www.researchgate.net/publication/369000045_Scaling_Law" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bc_2 .d-none}
```{=html}
<pre><code>@inbook{Basu2023,
  title = {Scaling Law},
  ISBN = {9780735424395},
  url = {http://dx.doi.org/10.1063/9780735424395_002},
  DOI = {10.1063/9780735424395_002},
  booktitle = {MEMS Applications in Electronics and Engineering},
  publisher = {AIP Publishing},
  author = {Basu,  Aviru Kumar and Bhattacharyya,  Suparno},
  year = {2023},
  pages = {1–14}
}</code></pre>
```
:::

::: {#abstract-bc_2 .d-none}
<p>DESCRIPTION Miniaturization is a rapidly growing methodology to produce extremely small mechanical, electronic, and optical devices, including semiconductor chips, typically built inside computers, vehicles, microprocessors, etc. Scaling laws provide fundamentals of the miniaturization. Scaling is a significant term nowadays in the design, simulation and fabrication of sensors and devices. In this chapter, the significance of physical laws is discussed and its significance in the design of various objects and structures at microscopic scales is discussed. Scaling laws for different types of forces are also presented. Scaling laws for various types of flexural joints are also presented, as they play a fundamental role in building the micro-structural systems. This chapter discusses the fundamentals of different scaling laws applicable in different fields of science and technology.</p>
:::
:::::
::::::

:::::: {.pub-item data-year="2021" data-type="Book Chapter"}
[📄]{.pub-icon}

::::: pub-content
Kumar, A.,**Bhattacharyya S.** (2021B).\
*MEMS Applications in Biology and Healthcare.*\
[Methods and Materials for Advanced Manufacturing (MMAM) of MEMS/NEMS-Enabled Bio-Electronics and Wearables for Health Monitoring](#){target="_blank"}

<a href="#" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Cite" data-modal-content="#cite-bc_1">Cite</a> <a href="#" class="btn btn-outline btn-sm" data-bs-toggle="modal" data-bs-target="#publication-modal" data-modal-title="Abstract" data-modal-content="#abstract-bc_1">Abstract</a> <a href="https://www.researchgate.net/publication/357362168_Methods_and_Materials_for_Advanced_Manufacturing_MMAM_of_MEMSNEMS-Enabled_Bioelectronics_and_Wearables_for_Health_Monitoring" class="btn btn-outline btn-sm" target="_blank">URL</a>

::: {#cite-bc_1 .d-none}
```{=html}
<pre><code>@inbook{Kumar2021,
  title = {Methods and Materials for Advanced Manufacturing (MMAM) of MEMS/NEMS-Enabled Bioelectronics and Wearables for Health Monitoring},
  ISBN = {9780735423954},
  url = {http://dx.doi.org/10.1063/9780735423954_009},
  DOI = {10.1063/9780735423954_009},
  booktitle = {MEMS Applications in Biology and Healthcare},
  publisher = {AIP Publishing},
  author = {Kumar,  Arkadeep and Bhattacharyya,  Suparno},
  year = {2021},
  pages = {1–24}
}</code></pre>
```
:::

::: {#abstract-bc_1 .d-none}
<p>DESCRIPTION With the advent of miniaturized bioelectronics, MEMS and NEMS have become an indispensable part of designers' toolbox in many areas of application. The rise of wearable technologies in various areas such as ubiquitous computing, along with smart monitoring of human health, has given rise to new concepts such as the Internet-of-body, wearable health monitoring, etc. To meet the ever-increasing demands of continuous health monitoring, these devices should always be fully functional and be able to track multiple health parameters, and also do these at the lowest possible power consumption for highest battery life. Further, the device data management should be efficient, with a provision for onboard memory/cloud sync etc. and devices should have high reliability levels. Moreover, emerging wearable MEMS/NEMS technology enabled devices need to be capable of learning the user's preference through the use of machine learning algorithms (ML), and thus leverage benefits of artificial intelligence in routine functioning. To realize such devices, rapid development in manufacturing process and materials are critical. In this work we have reviewed the latest developments in manufacturing MEMS/NEMS-enabled bioelectronic wearable devices, and have presented perspectives and prospects of such devices along with highlighting the important research directions.</p>
:::
:::::
::::::

## Presentations

:::: {.pub-item data-year="2025" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
**Bhattacharyya S.**, Tao J., Bukkapatnam S., Lodi S.G., Dargush G.F. (2025P).\
[Bandgap Optimization in Symmetry-Driven 3D Lattice Metamaterials](#){target="_blank"}\
18th U. S. National Congress on Computational Mechanics: July 20-24, 2025, Chicago, Illinois.
:::
::::

:::: {.pub-item data-year="2024" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
**Bhattacharyya S.**, Tao J., Gildin E., Ragusa J. (2024P).\
[Uncertainty Quantification With Hyper-Reduced Order Model](#){target="_blank"}\
ASME Verification, Validation, and Uncertainty Quantification Symposium 2024: May 15-17, 2024, College Station, Texas.
:::
::::

:::: {.pub-item data-year="2023" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
**Bhattacharyya S.**, Tao J., Gildin E., Ragusa J. (2023P).\
[Model Reduction of a Piecewise Nonlinear Mechanical Oscillator](#){target="_blank"}\
6th Annual Meeting of the SIAM Texas-Louisiana Section (TXLA23): Nov 3-5, 2023, Lafayette, Louisiana.
:::
::::

:::: {.pub-item data-year="2023" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
**Bhattacharyya S.**, Cusumano J. (2023P).\
[Model Reduction of a Piecewise Nonlinear Mechanical Oscillator](#){target="_blank"}\
17th U. S. National Congress on Computational Mechanics: July 23-27, 2023, Albuquerque, New Mexico.
:::
::::

:::: {.pub-item data-year="2018" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
**Bhattacharyya S.**, Alsalih H.∗, Choi Y., Lee K., Rai R. (2023P).\
[Data-Driven Model Discovery of Flexible Structures](#){target="_blank"}\
17th U. S. National Congress on Computational Mechanics: July 23-27, 2023, Albuquerque, New Mexico.
:::
::::

:::: {.pub-item data-year="2018" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
**Bhattacharyya S.**, Cusumano J. (2018P).\
[Energy criterion for enhanced accuracy of Reduced Order Models](#){target="_blank"}\
ESM Today 2018, Penn State University, USA.
:::
::::

:::: {.pub-item data-year="2011" data-type="Presentation"}
[📄]{.pub-icon}

::: pub-content
Kumar A., Chatterjee K., **Bhattacharyya S.** (2011P).\
[A review on corrosion control methods with electroless coatings](#){target="_blank"}\
National symposium of micro and nano characterization of materials 2011, Jadavpur University, India. (Obtained 2nd prize)
:::
::::
