---
title: "Publications"
listing:
  type: grid
  sort: "date desc"
  filter-ui: true
  fields: [title, authors, article, date]
  contents:
    - path: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=7ZsPlgYAAAAJ&sortby=pubdate&citation_for_view=7ZsPlgYAAAAJ:0EnyYjriUFMC
      title: "DensityEfficient dynamic topology optimization of 2D metamaterials based on a complementary energy formulation"
      authors: [Raj Pradip Khawale, Suparno Bhattacharyya, Rahul Rai, Gary F Dargush]
      article: "Computers & Structures (IF: 4.4, acceptance rate 8%)"
      date: "2024"
---

---
title: "Publications"
page-layout: full
title-block-banner: false
listing:
  id: publications-listing
  contents:
    - path: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=7ZsPlgYAAAAJ&sortby=pubdate&citation_for_view=7ZsPlgYAAAAJ:0EnyYjriUFMC
      title: "Efficient dynamic topology optimization of 2D metamaterials based on a complementary energy formulation"
      authors: "Raj Pradip Khawale, Suparno Bhattacharyya, Rahul Rai, Gary F Dargush"
      article: "Computers & Structures (IF: 4.4, acceptance rate 8%)"
      date: "2024"
      year: 2024
    - path: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=7ZsPlgYAAAAJ&sortby=pubdate&citation_for_view=7ZsPlgYAAAAJ:eQOLeE2rZwMC
      title: "Experimental implementation of energy closure analysis for reduced order modeling"
      authors: "Suparno Bhattacharyya, Joseph Cusumano"
      article: "ASME, Journal of Vibration and Acoustics (IF: 1.7)"
      date: "2022" 
      year: 2023
    - path: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=7ZsPlgYAAAAJ&sortby=pubdate&citation_for_view=7ZsPlgYAAAAJ:Y0pCki6q_DkC
      title: "An energy closure criterion for model reduction of a kicked Euler–Bernoulli beam"
      authors: "Suparno Bhattacharyya, Joseph P Cusumano"
      article: "ASME, Journal of Vibration and Acoustics (IF: 1.7, 2.1 at the time of submission)"
      date:  "01/08/2021"
      year: 2021
        
  type: table
  table-hover: true
  sort-ui: [year]
  filter-ui: [year, authors]
  sort: "year desc"
  max-description-length: 200
  fields: [title, authors, article, date]
  field-display-names:
    title: "Title"
    authors: "Authors"
    article: "Article"
    date: "Publication Date"
format:
  html:
    css: publications.css
    theme: {light: cosmo, dark: darkly}
---
